### ISSUE TITLE
Dependency: cx_freeze

### ISSUE THREAD

**Issue by mantielero** [openmodal/OpenModal#26]
Installing under ArchLinux it complains about missing cx_Freeze.

Solved by installing manually:
`$ yaourt -S python2-cx_freeze`

This probably should be managed in **setup.py**.

**Comment by jankoslavic** [comment]
Is this related to py2 only?

**Comment by mantielero** [comment]
The problem applies to both py2 and py3. I believe it should request that dependency.

Nonetheless, I think that the problem is bigger than what I stated. Once the dependency is installed, it complains about:
`cx_Freeze.freezer.ConfigError: cannot find file/directory named C:\Users\Matjaz\Anaconda3\Lib\site-packages\scipy\special\_ufuncs.cp35-win_amd64.pyd`

I think **setup.py** is too tailored to your specific Anaconda3 instalation.

Cheers

**Comment by matmr** [comment]
Hi @mantielero 

I'm kind of late with this, a lot of stuff going on ...

It seems that setup.py references the anaconda library a lot. Not sure why we went that way then, but might be because there were all kinds of trouble with cx_freeze. It was a 'hacky' solution.

Since you seem proficient with package manager and linux you are probably better off just running openmodal.py from the terminal.

On a side note, lately I had very good experience with [nuitka](http://nuitka.net/) and I might try to use it instead of cx_freeze in the future. Very little scripting is needed to run it and it somehow just works. If you want to try it yourself it should be relatively easy, of course the setup.py should be rewritten (cleaned up really).

So far we mostly used the software on Windows computers and we did not test much on Linux. Expect the future versions to be tested on Linux also, since I permanently switched systems just recently.

Please allow some time for things to improve. This is a project we work on in our free time and we could use an extra pair of hands. If you feel like you could improve on the setup situation, we'd be thrilled. Just do a pull request.


take care,
mm
